/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './crime-in-the-city.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './crime-in-the-city.component.css.shim';
const nodeDebugInfos_CrimeInTheCityComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.CrimeInTheCityComponent],import1.CrimeInTheCityComponent,{})];
var renderType_CrimeInTheCityComponent_Host:import2.RenderComponentType = (null as any);
class _View_CrimeInTheCityComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _CrimeInTheCityComponent_0_4:import1.CrimeInTheCityComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_CrimeInTheCityComponent_Host0,renderType_CrimeInTheCityComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_CrimeInTheCityComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-crime-in-the-city',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CrimeInTheCityComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CrimeInTheCityComponent_0_4 = new import1.CrimeInTheCityComponent();
    this._appEl_0.initComponent(this._CrimeInTheCityComponent_0_4,[],compView_0);
    compView_0.create(this._CrimeInTheCityComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.CrimeInTheCityComponent) && (0 === requestNodeIndex))) { return this._CrimeInTheCityComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._CrimeInTheCityComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_CrimeInTheCityComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_CrimeInTheCityComponent_Host === (null as any))) { (renderType_CrimeInTheCityComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_CrimeInTheCityComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CrimeInTheCityComponentNgFactory:import10.ComponentFactory<import1.CrimeInTheCityComponent> = new import10.ComponentFactory<import1.CrimeInTheCityComponent>('app-crime-in-the-city',viewFactory_CrimeInTheCityComponent_Host0,import1.CrimeInTheCityComponent);
const styles_CrimeInTheCityComponent:any[] = [import11.styles];
const nodeDebugInfos_CrimeInTheCityComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_CrimeInTheCityComponent:import2.RenderComponentType = (null as any);
class _View_CrimeInTheCityComponent0 extends import3.DebugAppView<import1.CrimeInTheCityComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_CrimeInTheCityComponent0,renderType_CrimeInTheCityComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_CrimeInTheCityComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,' Crime in the City ',this.debug(1,0,4));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',this.debug(2,0,28));
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_CrimeInTheCityComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.CrimeInTheCityComponent> {
  if ((renderType_CrimeInTheCityComponent === (null as any))) { (renderType_CrimeInTheCityComponent = viewUtils.createRenderComponentType('/Users/vrufu1/git-play/my-india-aot/app/layouts/crime-in-the-city/crime-in-the-city.component.html',0,import9.ViewEncapsulation.Emulated,styles_CrimeInTheCityComponent,{})); }
  return new _View_CrimeInTheCityComponent0(viewUtils,parentInjector,declarationEl);
}