/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './side-bar.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './side-bar.component.css.shim';
const nodeDebugInfos_SideBarComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.SideBarComponent],import1.SideBarComponent,{})];
var renderType_SideBarComponent_Host:import2.RenderComponentType = (null as any);
class _View_SideBarComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _SideBarComponent_0_4:import1.SideBarComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SideBarComponent_Host0,renderType_SideBarComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SideBarComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('div',rootSelector,this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','col-2');
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SideBarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SideBarComponent_0_4 = new import1.SideBarComponent();
    this._appEl_0.initComponent(this._SideBarComponent_0_4,[],compView_0);
    compView_0.create(this._SideBarComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.SideBarComponent) && (0 === requestNodeIndex))) { return this._SideBarComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SideBarComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SideBarComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_SideBarComponent_Host === (null as any))) { (renderType_SideBarComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_SideBarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SideBarComponentNgFactory:import10.ComponentFactory<import1.SideBarComponent> = new import10.ComponentFactory<import1.SideBarComponent>('.col-2',viewFactory_SideBarComponent_Host0,import1.SideBarComponent);
const styles_SideBarComponent:any[] = [import11.styles];
const nodeDebugInfos_SideBarComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_SideBarComponent:import2.RenderComponentType = (null as any);
class _View_SideBarComponent0 extends import3.DebugAppView<import1.SideBarComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_SideBarComponent0,renderType_SideBarComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SideBarComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'aside',this.debug(1,1,2));
    this.renderer.setElementAttribute(this._el_1,'class','side-bar');
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',this.debug(2,1,26));
    this._el_3 = this.renderer.createElement(this._el_1,'a',this.debug(3,2,2));
    this.renderer.setElementAttribute(this._el_3,'class','site-logo');
    this.renderer.setElementAttribute(this._el_3,'href','');
    this._el_4 = this.renderer.createElement(this._el_3,'img',this.debug(4,2,31));
    this.renderer.setElementAttribute(this._el_4,'alt','My India Logo');
    this.renderer.setElementAttribute(this._el_4,'src','site-logo.png');
    this._text_5 = this.renderer.createText(this._el_1,'\n  ',this.debug(5,2,81));
    this._el_6 = this.renderer.createElement(this._el_1,'nav',this.debug(6,3,2));
    this.renderer.setElementAttribute(this._el_6,'class','main-nav');
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',this.debug(7,3,24));
    this._el_8 = this.renderer.createElement(this._el_6,'ul',this.debug(8,4,4));
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',this.debug(9,4,8));
    this._el_10 = this.renderer.createElement(this._el_8,'li',this.debug(10,5,6));
    this._el_11 = this.renderer.createElement(this._el_10,'a',this.debug(11,5,10));
    this.renderer.setElementAttribute(this._el_11,'routerLink','/our-leaders');
    this._text_12 = this.renderer.createText(this._el_11,'Our Leaders',this.debug(12,5,39));
    this._text_13 = this.renderer.createText(this._el_8,'\n      ',this.debug(13,5,59));
    this._el_14 = this.renderer.createElement(this._el_8,'li',this.debug(14,6,6));
    this._el_15 = this.renderer.createElement(this._el_14,'a',this.debug(15,6,10));
    this.renderer.setElementAttribute(this._el_15,'routerLink','/crime-in-the-city');
    this._text_16 = this.renderer.createText(this._el_15,'Crime in Cities',this.debug(16,6,45));
    this._text_17 = this.renderer.createText(this._el_8,'\n      ',this.debug(17,6,69));
    this._el_18 = this.renderer.createElement(this._el_8,'li',this.debug(18,7,6));
    this._el_19 = this.renderer.createElement(this._el_18,'a',this.debug(19,7,10));
    this.renderer.setElementAttribute(this._el_19,'routerLink','');
    this._text_20 = this.renderer.createText(this._el_19,'Accidents in Cities',this.debug(20,7,27));
    this._text_21 = this.renderer.createText(this._el_8,'\n      ',this.debug(21,7,55));
    this._el_22 = this.renderer.createElement(this._el_8,'li',this.debug(22,8,6));
    this._el_23 = this.renderer.createElement(this._el_22,'a',this.debug(23,8,10));
    this.renderer.setElementAttribute(this._el_23,'routerLink','our-rivers');
    this._text_24 = this.renderer.createText(this._el_23,'Our Rivers',this.debug(24,8,37));
    this._text_25 = this.renderer.createText(this._el_8,'\n    ',this.debug(25,8,56));
    this._text_26 = this.renderer.createText(this._el_6,'\n  ',this.debug(26,9,9));
    this._text_27 = this.renderer.createText(this._el_1,'\n',this.debug(27,10,8));
    this._text_28 = this.renderer.createText(parentRenderNode,'\n\n  ',this.debug(28,11,8));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_SideBarComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.SideBarComponent> {
  if ((renderType_SideBarComponent === (null as any))) { (renderType_SideBarComponent = viewUtils.createRenderComponentType('/Users/vrufu1/git-play/my-india-aot/app/layouts/side-bar/side-bar.component.ts class SideBarComponent - inline template',0,import9.ViewEncapsulation.Emulated,styles_SideBarComponent,{})); }
  return new _View_SideBarComponent0(viewUtils,parentInjector,declarationEl);
}