/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.side-bar[_ngcontent-%COMP%] {\n  width: 100%;\n  height: 100%;\n  background-color: #2d3f4d;\n}\n\n.side-bar[_ngcontent-%COMP%]   .site-logo[_ngcontent-%COMP%] {\n  display: block;\n  background-color: #233440;\n  text-align: center;\n  cursor: pointer;\n}\n\n.side-bar[_ngcontent-%COMP%]   .main-nav[_ngcontent-%COMP%] {\n  padding: 20px 0;\n}\n\n.main-nav[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] {\n  margin: 0;\n  padding: 0 35px;\n}\n\n.main-nav[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]    > li[_ngcontent-%COMP%] {\n  padding: 15px 0;\n  list-style: none;\n}\n\n.main-nav[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]    > li[_ngcontent-%COMP%]    > a[_ngcontent-%COMP%] {\n  font-size: 16px;\n  font-family: Calibri, sans-serif;\n  color: #fff;\n  line-height: 20px;\n  text-decoration: none;\n}'];