/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.col-2[_ngcontent-%COMP%] {\n  width: 16%;\n  height: 100%;\n  float: left;\n}\n.col-10[_ngcontent-%COMP%] {\n  width: 84%;\n  float: left;\n}\nheader[_ngcontent-%COMP%] {\n  background-color: #fff;\n  height: 80px;\n  -webkit-box-shadow: 0 6px 3px -6px black;\n  -moz-box-shadow: 0 6px 3px -6px black;\n  box-shadow: 0 6px 3px -6px black;\n}\n.main-container[_ngcontent-%COMP%] {\n  padding: 20px 65px;\n}'];