/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './app.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './app.component.css.shim';
import * as import12 from './layouts/side-bar/side-bar.component';
import * as import13 from '@angular/router/src/directives/router_outlet';
import * as import14 from './layouts/side-bar/side-bar.component.ngfactory';
import * as import15 from '@angular/router/src/router_outlet_map';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
const nodeDebugInfos_AppComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.AppComponent],import1.AppComponent,{})];
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _AppComponent_0_4:import1.AppComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AppComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-root',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import1.AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4,[],compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import10.ComponentFactory<import1.AppComponent> = new import10.ComponentFactory<import1.AppComponent>('app-root',viewFactory_AppComponent_Host0,import1.AppComponent);
const styles_AppComponent:any[] = [import11.styles];
const nodeDebugInfos_AppComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([import12.SideBarComponent],import12.SideBarComponent,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import13.RouterOutlet],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import3.DebugAppView<import1.AppComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _SideBarComponent_0_4:import12.SideBarComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import4.AppElement;
  _RouterOutlet_9_5:import13.RouterOutlet;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AppComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','col-2');
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import14.viewFactory_SideBarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SideBarComponent_0_4 = new import12.SideBarComponent();
    this._appEl_0.initComponent(this._SideBarComponent_0_4,[],compView_0);
    compView_0.create(this._SideBarComponent_0_4,[],(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',this.debug(1,0,25));
    this._el_2 = this.renderer.createElement(parentRenderNode,'div',this.debug(2,1,0));
    this.renderer.setElementAttribute(this._el_2,'class','col-10');
    this._text_3 = this.renderer.createText(this._el_2,'\n  ',this.debug(3,1,20));
    this._el_4 = this.renderer.createElement(this._el_2,'header',this.debug(4,2,2));
    this._text_5 = this.renderer.createText(this._el_2,'\n  ',this.debug(5,2,19));
    this._el_6 = this.renderer.createElement(this._el_2,'div',this.debug(6,3,2));
    this.renderer.setElementAttribute(this._el_6,'class','main-container');
    this._text_7 = this.renderer.createText(this._el_6,'\n    GHJKHGCV\n    ',this.debug(7,3,30));
    this._text_8 = this.renderer.createText(this._el_6,'\n    ',this.debug(8,5,38));
    this._el_9 = this.renderer.createElement(this._el_6,'router-outlet',this.debug(9,6,4));
    this._appEl_9 = new import4.AppElement(9,6,this,this._el_9);
    this._RouterOutlet_9_5 = new import13.RouterOutlet(this.parentInjector.get(import15.RouterOutletMap),this._appEl_9.vcRef,this.parentInjector.get(import16.ComponentFactoryResolver),(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n  ',this.debug(10,6,35));
    this._text_11 = this.renderer.createText(this._el_2,'\n',this.debug(11,7,8));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n',this.debug(12,8,6));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.SideBarComponent) && (0 === requestNodeIndex))) { return this._SideBarComponent_0_4; }
    if (((token === import13.RouterOutlet) && (9 === requestNodeIndex))) { return this._RouterOutlet_9_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SideBarComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(9,6,4);
    this._RouterOutlet_9_5.ngOnDestroy();
  }
}
export function viewFactory_AppComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('/Users/vrufu1/git-play/my-india-aot/app/app.component.html',0,import9.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}