/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../shared/services/our-rivers.service';
import * as import2 from './our-rivers.component';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './our-rivers.component.css.shim';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '@angular/common/src/pipes/json_pipe';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
  const nodeDebugInfos_OurRiversComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([
    import1.OurRiversService,
    import2.OurRiversComponent
  ]
,import2.OurRiversComponent,{})];
var renderType_OurRiversComponent_Host:import3.RenderComponentType = (null as any);
class _View_OurRiversComponent_Host0 extends import4.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _OurRiversService_0_4:import1.OurRiversService;
  _OurRiversComponent_0_5:import2.OurRiversComponent;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_OurRiversComponent_Host0,renderType_OurRiversComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OurRiversComponent_Host0);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-our-rivers',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_OurRiversComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._OurRiversService_0_4 = new import1.OurRiversService(this.parentInjector.get(import10.Http));
    this._OurRiversComponent_0_5 = new import2.OurRiversComponent(this._OurRiversService_0_4);
    this._appEl_0.initComponent(this._OurRiversComponent_0_5,[],compView_0);
    compView_0.create(this._OurRiversComponent_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.OurRiversService) && (0 === requestNodeIndex))) { return this._OurRiversService_0_4; }
    if (((token === import2.OurRiversComponent) && (0 === requestNodeIndex))) { return this._OurRiversComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._OurRiversComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OurRiversComponent_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import4.AppView<any> {
  if ((renderType_OurRiversComponent_Host === (null as any))) { (renderType_OurRiversComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_OurRiversComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const OurRiversComponentNgFactory:import12.ComponentFactory<import2.OurRiversComponent> = new import12.ComponentFactory<import2.OurRiversComponent>('app-our-rivers',viewFactory_OurRiversComponent_Host0,import2.OurRiversComponent);
const styles_OurRiversComponent:any[] = [import13.styles];
const nodeDebugInfos_OurRiversComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import14.TemplateRef,
    import15.NgFor
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_OurRiversComponent:import3.RenderComponentType = (null as any);
class _View_OurRiversComponent0 extends import4.DebugAppView<import2.OurRiversComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import5.AppElement;
  _TemplateRef_31_5:any;
  _NgFor_31_6:import15.NgFor;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  /*private*/ _expr_0:any;
  _pipe_json_0:import16.JsonPipe;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_OurRiversComponent0,renderType_OurRiversComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OurRiversComponent0);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,' Our Rivers ',this.debug(1,0,4));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n\n\n',this.debug(2,0,21));
    this._el_3 = this.renderer.createElement(parentRenderNode,'table',this.debug(3,4,0));
    this._text_4 = this.renderer.createText(this._el_3,'\n  ',this.debug(4,4,7));
    this._el_5 = this.renderer.createElement(this._el_3,'thead',this.debug(5,5,2));
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',this.debug(6,5,9));
    this._el_7 = this.renderer.createElement(this._el_5,'tr',this.debug(7,6,4));
    this._text_8 = this.renderer.createText(this._el_7,'\n',this.debug(8,6,8));
    this._el_9 = this.renderer.createElement(this._el_7,'th',this.debug(9,7,0));
    this._text_10 = this.renderer.createText(this._el_9,'Sate',this.debug(10,7,4));
    this._text_11 = this.renderer.createText(this._el_7,'\n',this.debug(11,7,13));
    this._el_12 = this.renderer.createElement(this._el_7,'th',this.debug(12,8,0));
    this._text_13 = this.renderer.createText(this._el_12,'Location',this.debug(13,8,4));
    this._text_14 = this.renderer.createText(this._el_7,'\n',this.debug(14,8,17));
    this._el_15 = this.renderer.createElement(this._el_7,'th',this.debug(15,9,0));
    this._text_16 = this.renderer.createText(this._el_15,'Max Temp ',this.debug(16,9,4));
    this._text_17 = this.renderer.createText(this._el_7,'\n',this.debug(17,9,18));
    this._el_18 = this.renderer.createElement(this._el_7,'th',this.debug(18,10,0));
    this._text_19 = this.renderer.createText(this._el_18,'Min Temp.',this.debug(19,10,4));
    this._text_20 = this.renderer.createText(this._el_7,'\n',this.debug(20,10,18));
    this._el_21 = this.renderer.createElement(this._el_7,'th',this.debug(21,11,0));
    this._text_22 = this.renderer.createText(this._el_21,'PH Value Max',this.debug(22,11,4));
    this._text_23 = this.renderer.createText(this._el_7,'\n',this.debug(23,11,21));
    this._el_24 = this.renderer.createElement(this._el_7,'th',this.debug(24,12,0));
    this._text_25 = this.renderer.createText(this._el_24,'PH Value Min',this.debug(25,12,4));
    this._text_26 = this.renderer.createText(this._el_7,'\n    ',this.debug(26,12,21));
    this._text_27 = this.renderer.createText(this._el_5,'\n  ',this.debug(27,13,9));
    this._text_28 = this.renderer.createText(this._el_3,'\n\n  ',this.debug(28,14,10));
    this._el_29 = this.renderer.createElement(this._el_3,'tbody',this.debug(29,16,2));
    this._text_30 = this.renderer.createText(this._el_29,'\n     \n    ',this.debug(30,16,9));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_29,this.debug(31,18,4));
    this._appEl_31 = new import5.AppElement(31,29,this,this._anchor_31);
    this._TemplateRef_31_5 = new import14.TemplateRef_(this._appEl_31,viewFactory_OurRiversComponent1);
    this._NgFor_31_6 = new import15.NgFor(this._appEl_31.vcRef,this._TemplateRef_31_5,this.parentInjector.get(import17.IterableDiffers),this.ref);
    this._text_32 = this.renderer.createText(this._el_3,'\n',this.debug(32,26,10));
    this._text_33 = this.renderer.createText(parentRenderNode,' \n\n\n',this.debug(33,27,8));
    this._el_34 = this.renderer.createElement(parentRenderNode,'hr',this.debug(34,30,0));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(35,30,5));
    this._el_36 = this.renderer.createElement(parentRenderNode,'pre',this.debug(36,32,0));
    this._text_37 = this.renderer.createText(this._el_36,'',this.debug(37,32,5));
    this._expr_0 = import9.UNINITIALIZED;
    this.debug((null as any),(null as any),(null as any));
    this._pipe_json_0 = new import16.JsonPipe();
    this._expr_1 = import9.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import15.NgFor) && (31 === requestNodeIndex))) { return this._NgFor_31_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    const valUnwrapper:any = new import9.ValueUnwrapper();
    this.debug(31,18,4);
    changes = (null as any);
    this.debug(31,18,8);
    const currVal_0:any = this.context.riversData;
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_31_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_31_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_31_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(37,32,5);
    valUnwrapper.reset();
    const currVal_1:any = import6.interpolate(1,'    ',valUnwrapper.unwrap(this._pipe_json_0.transform(this.context.riversData)),'\n    ');
    if ((valUnwrapper.hasWrappedValue || import6.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setText(this._text_37,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_OurRiversComponent0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import4.AppView<import2.OurRiversComponent> {
  if ((renderType_OurRiversComponent === (null as any))) { (renderType_OurRiversComponent = viewUtils.createRenderComponentType('/Users/vrufu1/git-play/my-india-aot/app/layouts/our-rivers/our-rivers.component.html',0,import11.ViewEncapsulation.Emulated,styles_OurRiversComponent,{})); }
  return new _View_OurRiversComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_OurRiversComponent1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_OurRiversComponent1 extends import4.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_OurRiversComponent1,renderType_OurRiversComponent,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OurRiversComponent1);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',this.debug(0,18,4));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',this.debug(1,18,40));
    this._el_2 = this.renderer.createElement(this._el_0,'td',this.debug(2,19,6));
    this._text_3 = this.renderer.createText(this._el_2,'',this.debug(3,19,10));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',this.debug(4,19,29));
    this._el_5 = this.renderer.createElement(this._el_0,'td',this.debug(5,20,6));
    this._text_6 = this.renderer.createText(this._el_5,'',this.debug(6,20,10));
    this._text_7 = this.renderer.createText(this._el_0,'\n      ',this.debug(7,20,33));
    this._el_8 = this.renderer.createElement(this._el_0,'td',this.debug(8,21,6));
    this._text_9 = this.renderer.createText(this._el_8,'',this.debug(9,21,10));
    this._text_10 = this.renderer.createText(this._el_0,'\n      ',this.debug(10,21,56));
    this._el_11 = this.renderer.createElement(this._el_0,'td',this.debug(11,22,6));
    this._text_12 = this.renderer.createText(this._el_11,'',this.debug(12,22,10));
    this._text_13 = this.renderer.createText(this._el_0,'\n      ',this.debug(13,22,56));
    this._el_14 = this.renderer.createElement(this._el_0,'td',this.debug(14,23,6));
    this._text_15 = this.renderer.createText(this._el_14,'',this.debug(15,23,10));
    this._text_16 = this.renderer.createText(this._el_0,'\n      ',this.debug(16,23,33));
    this._el_17 = this.renderer.createElement(this._el_0,'td',this.debug(17,24,6));
    this._text_18 = this.renderer.createText(this._el_17,'',this.debug(18,24,10));
    this._text_19 = this.renderer.createText(this._el_0,'\n    \n  ',this.debug(19,24,33));
    this._expr_0 = import9.UNINITIALIZED;
    this._expr_1 = import9.UNINITIALIZED;
    this._expr_2 = import9.UNINITIALIZED;
    this._expr_3 = import9.UNINITIALIZED;
    this._expr_4 = import9.UNINITIALIZED;
    this._expr_5 = import9.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(3,19,10);
    const currVal_0:any = import6.interpolate(1,'',this.context.$implicit.STATE,'');
    if (import6.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.debug(6,20,10);
    const currVal_1:any = import6.interpolate(1,'',this.context.$implicit.LOCATIONS,'');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.debug(9,21,10);
    const currVal_2:any = import6.interpolate(1,'',this.context.$implicit.TEMPERATUREInDegreeCentigradeMax,'');
    if (import6.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.debug(12,22,10);
    const currVal_3:any = import6.interpolate(1,'',this.context.$implicit.TEMPERATUREInDegreeCentigradeMin,'');
    if (import6.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_12,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.debug(15,23,10);
    const currVal_4:any = import6.interpolate(1,'',this.context.$implicit.PH6585Max,'');
    if (import6.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_15,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.debug(18,24,10);
    const currVal_5:any = import6.interpolate(1,'',this.context.$implicit.PH6585Min,'');
    if (import6.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_18,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OurRiversComponent1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import4.AppView<any> {
  return new _View_OurRiversComponent1(viewUtils,parentInjector,declarationEl);
}